export const s = {
  page:      { padding: '2rem' },
  header:    { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' },
  title:     { color: '#e94560', margin: 0 },
  btn:       { padding: '0.5rem 1.25rem', background: '#e94560', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer' },
  smBtn:     { padding: '3px 10px', background: '#e94560', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '0.8rem' },
  cancelBtn: { padding: '0.5rem 1.25rem', background: 'transparent', color: '#ccc', border: '1px solid #555', borderRadius: '6px', cursor: 'pointer' },
  grid:      { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '1rem' },
  card:      { background: '#1a1a2e', borderRadius: '10px', padding: '1.25rem' },
  cardTitle: { color: '#e94560', margin: '0 0 0.5rem' },
  cardMeta:  { color: '#888', margin: '0 0 0.25rem', fontSize: '0.85rem' },
  table:     { width: '100%', borderCollapse: 'collapse' },
  th:        { textAlign: 'left', padding: '0.75rem', borderBottom: '2px solid #333', color: '#888', fontSize: '0.85rem', textTransform: 'uppercase' },
  tr:        { borderBottom: '1px solid #222' },
  td:        { padding: '0.75rem', color: '#ddd', fontSize: '0.9rem' },
  overlay:   { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  modal:     { background: '#1a1a2e', borderRadius: '12px', padding: '2rem', width: '650px', maxWidth: '95vw', maxHeight: '90vh', overflowY: 'auto' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' },
  closeBtn:  { background: 'none', border: 'none', color: '#888', fontSize: '1.25rem', cursor: 'pointer' },
  formGrid:  { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' },
  label:     { display: 'block', color: '#aaa', fontSize: '0.8rem', marginBottom: '0.3rem' },
  input:     { width: '100%', padding: '0.5rem', borderRadius: '6px', border: '1px solid #333', background: '#0f0f1a', color: '#fff', boxSizing: 'border-box' },
  search:    { padding: '0.5rem 0.75rem', borderRadius: '6px', border: '1px solid #333', background: '#0f0f1a', color: '#fff' },
};
